version: 0.0.1.{build}

init:
    - git config --global core.autocrlf true
  
branches:
  only:
    - master
    - dev

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

build:
  publish_nuget: true               # package projects with .nuspec files and push to artifacts
  publish_nuget_symbols: false      # generate and publish NuGet symbol packages
  verbosity: minimal                # MSBuild verbosity level

before_build:
 - ps: nuget restore Skyland.Pipeline.sln

after_build:
 - ps: nuget pack .\src\Skyland.Pipeline\Skyland.Pipeline.nuspec

artifacts:
 - path: '**\*.nupkg'
   name: Nuget
   
deploy:
  provider: NuGet
  server: https://ci.appveyor.com/nuget/josemiguelrodriguezg-eho7mf708t5v/api/v2/package
  api_key:
    secure: Hy5t86+y81dw7mFq3nXivEFNWmhBvE1kKVqMrn2D5FY=
  skip_symbols: true
  
# build cache to preserve files/folders between builds
cache:
  - packages -> **\packages.config  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified
  - '%LocalAppData%\NuGet\Cache'

